#############################################################################
# Makefile for building: TestConsole
# Generated by qmake (3.0) (Qt 5.5.1)
# Project:  TestConsole.pro
# Template: app
# Command: /usr/lib/x86_64-linux-gnu/qt5/bin/qmake -spec linux-g++-64 -o Makefile TestConsole.pro
#############################################################################

MAKEFILE      = Makefile

####### Compiler, tools and options

CC            = gcc
CXX           = g++
DEFINES       = -DQT_NO_DEBUG -DQT_WIDGETS_LIB -DQT_WEBKIT_LIB -DQT_GUI_LIB -DQT_NETWORK_LIB -DQT_XML_LIB -DQT_SERIALPORT_LIB -DQT_CORE_LIB
CFLAGS        = -m64 -pipe -O2 -Wall -W -D_REENTRANT -fPIC $(DEFINES)
CXXFLAGS      = -m64 -pipe -O2 -Wall -W -D_REENTRANT -fPIC $(DEFINES)
INCPATH       = -I. -Imavlink -isystem /usr/include/x86_64-linux-gnu/qt5 -isystem /usr/include/x86_64-linux-gnu/qt5/QtWidgets -isystem /usr/include/x86_64-linux-gnu/qt5/QtWebKit -isystem /usr/include/x86_64-linux-gnu/qt5/QtGui -isystem /usr/include/x86_64-linux-gnu/qt5/QtNetwork -isystem /usr/include/x86_64-linux-gnu/qt5/QtXml -isystem /usr/include/x86_64-linux-gnu/qt5/QtSerialPort -isystem /usr/include/x86_64-linux-gnu/qt5/QtCore -I. -I. -I/usr/lib/x86_64-linux-gnu/qt5/mkspecs/linux-g++-64
QMAKE         = /usr/lib/x86_64-linux-gnu/qt5/bin/qmake
DEL_FILE      = rm -f
CHK_DIR_EXISTS= test -d
MKDIR         = mkdir -p
COPY          = cp -f
COPY_FILE     = cp -f
COPY_DIR      = cp -f -R
INSTALL_FILE  = install -m 644 -p
INSTALL_PROGRAM = install -m 755 -p
INSTALL_DIR   = cp -f -R
DEL_FILE      = rm -f
SYMLINK       = ln -f -s
DEL_DIR       = rmdir
MOVE          = mv -f
TAR           = tar -cf
COMPRESS      = gzip -9f
DISTNAME      = TestConsole1.0.0
DISTDIR = /home/mango/myQT/TestConsole1.1/.tmp/TestConsole1.0.0
LINK          = g++
LFLAGS        = -m64 -Wl,-O1 -Wl,-rpath-link,/usr/lib/x86_64-linux-gnu
LIBS          = $(SUBLIBS) -L/usr/X11R6/lib64 -lQt5Widgets -lQt5WebKit -lQt5Gui -lQt5Network -lQt5Xml -lQt5SerialPort -lQt5Core -lGL -lpthread 
AR            = ar cqs
RANLIB        = 
SED           = sed
STRIP         = strip

####### Output directory

OBJECTS_DIR   = ./

####### Files

SOURCES       = main.cpp \
		mainwindow.cpp \
		led.cpp \
		mav.cpp \
		mav_udp.cpp \
		uart_robot.cpp \
		uart_rf433.cpp \
		xml.cpp \
		TestResult.cpp qrc_image.cpp \
		moc_mainwindow.cpp \
		moc_led.cpp \
		moc_mav.cpp \
		moc_mav_udp.cpp \
		moc_uart_robot.cpp \
		moc_uart_rf433.cpp \
		moc_xml.cpp \
		moc_TestResult.cpp
OBJECTS       = main.o \
		mainwindow.o \
		led.o \
		mav.o \
		mav_udp.o \
		uart_robot.o \
		uart_rf433.o \
		xml.o \
		TestResult.o \
		qrc_image.o \
		moc_mainwindow.o \
		moc_led.o \
		moc_mav.o \
		moc_mav_udp.o \
		moc_uart_robot.o \
		moc_uart_rf433.o \
		moc_xml.o \
		moc_TestResult.o
DIST          = /usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/spec_pre.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/unix.conf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/linux.conf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/sanitize.conf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/gcc-base.conf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/gcc-base-unix.conf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/g++-base.conf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/g++-unix.conf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/qconfig.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_bootstrap_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_clucene_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_concurrent.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_concurrent_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_core.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_core_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_dbus.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_dbus_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_designer.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_designer_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_designercomponents_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_eglfs_device_lib_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_gui.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_gui_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_help.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_help_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_multimedia.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_multimediawidgets.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_network.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_network_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_opengl.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_opengl_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_openglextensions.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_openglextensions_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_platformsupport_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_printsupport.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_printsupport_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_qml.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_qml_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_qmldevtools_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_qmltest.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_qmltest_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_quick.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_quick_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_quickparticles_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_quickwidgets.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_quickwidgets_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_script.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_script_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_scripttools.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_scripttools_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_serialport.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_sql.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_sql_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_svg.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_testlib.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_testlib_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_uiplugin.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_uitools.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_uitools_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_webkit.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_webkitwidgets.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_widgets.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_widgets_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_x11extras.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_xcb_qpa_lib_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_xml.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_xml_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_xmlpatterns.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_xmlpatterns_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/qt_functions.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/qt_config.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/linux-g++-64/qmake.conf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/spec_post.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/exclusive_builds.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/default_pre.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/resolve_config.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/default_post.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/warn_on.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/qt.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/resources.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/moc.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/unix/opengl.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/uic.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/unix/thread.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/testcase_targets.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/exceptions.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/yacc.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/lex.prf \
		TestConsole.pro mainwindow.h \
		led.h \
		mav.h \
		mav_udp.h \
		uart_robot.h \
		uart_rf433.h \
		xml.h \
		TestResult.h main.cpp \
		mainwindow.cpp \
		led.cpp \
		mav.cpp \
		mav_udp.cpp \
		uart_robot.cpp \
		uart_rf433.cpp \
		xml.cpp \
		TestResult.cpp
QMAKE_TARGET  = TestConsole
DESTDIR       = #avoid trailing-slash linebreak
TARGET        = TestConsole


first: all
####### Implicit rules

.SUFFIXES: .o .c .cpp .cc .cxx .C

.cpp.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.cc.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.cxx.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.C.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.c.o:
	$(CC) -c $(CFLAGS) $(INCPATH) -o "$@" "$<"

####### Build rules

$(TARGET): ui_mainwindow.h ui_dialog_test_result.h $(OBJECTS)  
	$(LINK) $(LFLAGS) -o $(TARGET) $(OBJECTS) $(OBJCOMP) $(LIBS)

Makefile: TestConsole.pro /usr/lib/x86_64-linux-gnu/qt5/mkspecs/linux-g++-64/qmake.conf /usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/spec_pre.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/unix.conf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/linux.conf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/sanitize.conf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/gcc-base.conf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/gcc-base-unix.conf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/g++-base.conf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/g++-unix.conf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/qconfig.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_bootstrap_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_clucene_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_concurrent.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_concurrent_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_core.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_core_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_dbus.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_dbus_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_designer.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_designer_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_designercomponents_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_eglfs_device_lib_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_gui.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_gui_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_help.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_help_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_multimedia.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_multimediawidgets.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_network.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_network_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_opengl.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_opengl_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_openglextensions.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_openglextensions_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_platformsupport_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_printsupport.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_printsupport_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_qml.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_qml_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_qmldevtools_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_qmltest.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_qmltest_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_quick.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_quick_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_quickparticles_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_quickwidgets.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_quickwidgets_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_script.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_script_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_scripttools.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_scripttools_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_serialport.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_sql.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_sql_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_svg.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_testlib.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_testlib_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_uiplugin.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_uitools.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_uitools_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_webkit.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_webkitwidgets.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_widgets.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_widgets_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_x11extras.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_xcb_qpa_lib_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_xml.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_xml_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_xmlpatterns.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_xmlpatterns_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/qt_functions.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/qt_config.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/linux-g++-64/qmake.conf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/spec_post.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/exclusive_builds.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/default_pre.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/resolve_config.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/default_post.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/warn_on.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/qt.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/resources.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/moc.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/unix/opengl.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/uic.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/unix/thread.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/testcase_targets.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/exceptions.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/yacc.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/lex.prf \
		TestConsole.pro \
		image.qrc \
		/usr/lib/x86_64-linux-gnu/libQt5Widgets.prl \
		/usr/lib/x86_64-linux-gnu/libQt5WebKit.prl \
		/usr/lib/x86_64-linux-gnu/libQt5Gui.prl \
		/usr/lib/x86_64-linux-gnu/libQt5Network.prl \
		/usr/lib/x86_64-linux-gnu/libQt5Xml.prl \
		/usr/lib/x86_64-linux-gnu/libQt5SerialPort.prl \
		/usr/lib/x86_64-linux-gnu/libQt5Core.prl
	$(QMAKE) -spec linux-g++-64 -o Makefile TestConsole.pro
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/spec_pre.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/unix.conf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/linux.conf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/sanitize.conf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/gcc-base.conf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/gcc-base-unix.conf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/g++-base.conf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/g++-unix.conf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/qconfig.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_bootstrap_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_clucene_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_concurrent.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_concurrent_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_core.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_core_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_dbus.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_dbus_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_designer.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_designer_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_designercomponents_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_eglfs_device_lib_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_gui.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_gui_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_help.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_help_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_multimedia.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_multimediawidgets.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_network.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_network_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_opengl.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_opengl_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_openglextensions.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_openglextensions_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_platformsupport_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_printsupport.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_printsupport_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_qml.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_qml_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_qmldevtools_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_qmltest.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_qmltest_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_quick.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_quick_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_quickparticles_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_quickwidgets.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_quickwidgets_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_script.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_script_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_scripttools.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_scripttools_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_serialport.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_sql.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_sql_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_svg.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_testlib.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_testlib_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_uiplugin.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_uitools.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_uitools_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_webkit.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_webkitwidgets.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_widgets.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_widgets_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_x11extras.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_xcb_qpa_lib_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_xml.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_xml_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_xmlpatterns.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_xmlpatterns_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/qt_functions.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/qt_config.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/linux-g++-64/qmake.conf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/spec_post.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/exclusive_builds.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/default_pre.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/resolve_config.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/default_post.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/warn_on.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/qt.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/resources.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/moc.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/unix/opengl.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/uic.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/unix/thread.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/testcase_targets.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/exceptions.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/yacc.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/lex.prf:
TestConsole.pro:
image.qrc:
/usr/lib/x86_64-linux-gnu/libQt5Widgets.prl:
/usr/lib/x86_64-linux-gnu/libQt5WebKit.prl:
/usr/lib/x86_64-linux-gnu/libQt5Gui.prl:
/usr/lib/x86_64-linux-gnu/libQt5Network.prl:
/usr/lib/x86_64-linux-gnu/libQt5Xml.prl:
/usr/lib/x86_64-linux-gnu/libQt5SerialPort.prl:
/usr/lib/x86_64-linux-gnu/libQt5Core.prl:
qmake: FORCE
	@$(QMAKE) -spec linux-g++-64 -o Makefile TestConsole.pro

qmake_all: FORCE


all: Makefile $(TARGET)

dist: distdir FORCE
	(cd `dirname $(DISTDIR)` && $(TAR) $(DISTNAME).tar $(DISTNAME) && $(COMPRESS) $(DISTNAME).tar) && $(MOVE) `dirname $(DISTDIR)`/$(DISTNAME).tar.gz . && $(DEL_FILE) -r $(DISTDIR)

distdir: FORCE
	@test -d $(DISTDIR) || mkdir -p $(DISTDIR)
	$(COPY_FILE) --parents $(DIST) $(DISTDIR)/
	$(COPY_FILE) --parents image.qrc $(DISTDIR)/
	$(COPY_FILE) --parents mainwindow.h led.h mav.h mav_udp.h uart_robot.h uart_rf433.h xml.h TestResult.h $(DISTDIR)/
	$(COPY_FILE) --parents main.cpp mainwindow.cpp led.cpp mav.cpp mav_udp.cpp uart_robot.cpp uart_rf433.cpp xml.cpp TestResult.cpp $(DISTDIR)/
	$(COPY_FILE) --parents mainwindow.ui dialog_test_result.ui $(DISTDIR)/


clean: compiler_clean 
	-$(DEL_FILE) $(OBJECTS)
	-$(DEL_FILE) *~ core *.core


distclean: clean 
	-$(DEL_FILE) $(TARGET) 
	-$(DEL_FILE) Makefile


####### Sub-libraries

mocclean: compiler_moc_header_clean compiler_moc_source_clean

mocables: compiler_moc_header_make_all compiler_moc_source_make_all

check: first

compiler_rcc_make_all: qrc_image.cpp
compiler_rcc_clean:
	-$(DEL_FILE) qrc_image.cpp
qrc_image.cpp: image.qrc \
		image/logo.png \
		image/pp.png \
		image/narwel.png
	/usr/lib/x86_64-linux-gnu/qt5/bin/rcc -name image image.qrc -o qrc_image.cpp

compiler_moc_header_make_all: moc_mainwindow.cpp moc_led.cpp moc_mav.cpp moc_mav_udp.cpp moc_uart_robot.cpp moc_uart_rf433.cpp moc_xml.cpp moc_TestResult.cpp
compiler_moc_header_clean:
	-$(DEL_FILE) moc_mainwindow.cpp moc_led.cpp moc_mav.cpp moc_mav_udp.cpp moc_uart_robot.cpp moc_uart_rf433.cpp moc_xml.cpp moc_TestResult.cpp
moc_mainwindow.cpp: mav.h \
		mavlink/common_extra_msg/mavlink.h \
		mavlink/common_extra_msg/version.h \
		mavlink/common_extra_msg/common_extra_msg.h \
		mavlink/protocol.h \
		mavlink/mavlink_types.h \
		mavlink/mavlink_helpers.h \
		mavlink/checksum.h \
		mavlink/mavlink_conversions.h \
		mavlink/common/common.h \
		mavlink/common/mavlink_msg_heartbeat.h \
		mavlink/common/mavlink_msg_sys_status.h \
		mavlink/common/mavlink_msg_system_time.h \
		mavlink/common/mavlink_msg_ping.h \
		mavlink/common/mavlink_msg_change_operator_control.h \
		mavlink/common/mavlink_msg_change_operator_control_ack.h \
		mavlink/common/mavlink_msg_auth_key.h \
		mavlink/common/mavlink_msg_set_mode.h \
		mavlink/common/mavlink_msg_param_request_read.h \
		mavlink/common/mavlink_msg_param_request_list.h \
		mavlink/common/mavlink_msg_param_value.h \
		mavlink/common/mavlink_msg_param_set.h \
		mavlink/common/mavlink_msg_gps_raw_int.h \
		mavlink/common/mavlink_msg_gps_status.h \
		mavlink/common/mavlink_msg_scaled_imu.h \
		mavlink/common/mavlink_msg_raw_imu.h \
		mavlink/common/mavlink_msg_raw_pressure.h \
		mavlink/common/mavlink_msg_scaled_pressure.h \
		mavlink/common/mavlink_msg_attitude.h \
		mavlink/common/mavlink_msg_attitude_quaternion.h \
		mavlink/common/mavlink_msg_local_position_ned.h \
		mavlink/common/mavlink_msg_global_position_int.h \
		mavlink/common/mavlink_msg_rc_channels_scaled.h \
		mavlink/common/mavlink_msg_rc_channels_raw.h \
		mavlink/common/mavlink_msg_servo_output_raw.h \
		mavlink/common/mavlink_msg_mission_request_partial_list.h \
		mavlink/common/mavlink_msg_mission_write_partial_list.h \
		mavlink/common/mavlink_msg_mission_item.h \
		mavlink/common/mavlink_msg_mission_request.h \
		mavlink/common/mavlink_msg_mission_set_current.h \
		mavlink/common/mavlink_msg_mission_current.h \
		mavlink/common/mavlink_msg_mission_request_list.h \
		mavlink/common/mavlink_msg_mission_count.h \
		mavlink/common/mavlink_msg_mission_clear_all.h \
		mavlink/common/mavlink_msg_mission_item_reached.h \
		mavlink/common/mavlink_msg_mission_ack.h \
		mavlink/common/mavlink_msg_set_gps_global_origin.h \
		mavlink/common/mavlink_msg_gps_global_origin.h \
		mavlink/common/mavlink_msg_param_map_rc.h \
		mavlink/common/mavlink_msg_mission_request_int.h \
		mavlink/common/mavlink_msg_safety_set_allowed_area.h \
		mavlink/common/mavlink_msg_safety_allowed_area.h \
		mavlink/common/mavlink_msg_attitude_quaternion_cov.h \
		mavlink/common/mavlink_msg_nav_controller_output.h \
		mavlink/common/mavlink_msg_global_position_int_cov.h \
		mavlink/common/mavlink_msg_local_position_ned_cov.h \
		mavlink/common/mavlink_msg_rc_channels.h \
		mavlink/common/mavlink_msg_request_data_stream.h \
		mavlink/common/mavlink_msg_data_stream.h \
		mavlink/common/mavlink_msg_manual_control.h \
		mavlink/common/mavlink_msg_rc_channels_override.h \
		mavlink/common/mavlink_msg_mission_item_int.h \
		mavlink/common/mavlink_msg_vfr_hud.h \
		mavlink/common/mavlink_msg_command_int.h \
		mavlink/common/mavlink_msg_command_long.h \
		mavlink/common/mavlink_msg_command_ack.h \
		mavlink/common/mavlink_msg_manual_setpoint.h \
		mavlink/common/mavlink_msg_set_attitude_target.h \
		mavlink/common/mavlink_msg_attitude_target.h \
		mavlink/common/mavlink_msg_set_position_target_local_ned.h \
		mavlink/common/mavlink_msg_position_target_local_ned.h \
		mavlink/common/mavlink_msg_set_position_target_global_int.h \
		mavlink/common/mavlink_msg_position_target_global_int.h \
		mavlink/common/mavlink_msg_local_position_ned_system_global_offset.h \
		mavlink/common/mavlink_msg_hil_state.h \
		mavlink/common/mavlink_msg_hil_controls.h \
		mavlink/common/mavlink_msg_hil_rc_inputs_raw.h \
		mavlink/common/mavlink_msg_optical_flow.h \
		mavlink/common/mavlink_msg_global_vision_position_estimate.h \
		mavlink/common/mavlink_msg_vision_position_estimate.h \
		mavlink/common/mavlink_msg_vision_speed_estimate.h \
		mavlink/common/mavlink_msg_vicon_position_estimate.h \
		mavlink/common/mavlink_msg_highres_imu.h \
		mavlink/common/mavlink_msg_optical_flow_rad.h \
		mavlink/common/mavlink_msg_hil_sensor.h \
		mavlink/common/mavlink_msg_sim_state.h \
		mavlink/common/mavlink_msg_radio_status.h \
		mavlink/common/mavlink_msg_file_transfer_protocol.h \
		mavlink/common/mavlink_msg_timesync.h \
		mavlink/common/mavlink_msg_camera_trigger.h \
		mavlink/common/mavlink_msg_hil_gps.h \
		mavlink/common/mavlink_msg_hil_optical_flow.h \
		mavlink/common/mavlink_msg_hil_state_quaternion.h \
		mavlink/common/mavlink_msg_scaled_imu2.h \
		mavlink/common/mavlink_msg_log_request_list.h \
		mavlink/common/mavlink_msg_log_entry.h \
		mavlink/common/mavlink_msg_log_request_data.h \
		mavlink/common/mavlink_msg_log_data.h \
		mavlink/common/mavlink_msg_log_erase.h \
		mavlink/common/mavlink_msg_log_request_end.h \
		mavlink/common/mavlink_msg_gps_inject_data.h \
		mavlink/common/mavlink_msg_gps2_raw.h \
		mavlink/common/mavlink_msg_power_status.h \
		mavlink/common/mavlink_msg_serial_control.h \
		mavlink/common/mavlink_msg_gps_rtk.h \
		mavlink/common/mavlink_msg_gps2_rtk.h \
		mavlink/common/mavlink_msg_scaled_imu3.h \
		mavlink/common/mavlink_msg_data_transmission_handshake.h \
		mavlink/common/mavlink_msg_encapsulated_data.h \
		mavlink/common/mavlink_msg_distance_sensor.h \
		mavlink/common/mavlink_msg_terrain_request.h \
		mavlink/common/mavlink_msg_terrain_data.h \
		mavlink/common/mavlink_msg_terrain_check.h \
		mavlink/common/mavlink_msg_terrain_report.h \
		mavlink/common/mavlink_msg_scaled_pressure2.h \
		mavlink/common/mavlink_msg_att_pos_mocap.h \
		mavlink/common/mavlink_msg_set_actuator_control_target.h \
		mavlink/common/mavlink_msg_actuator_control_target.h \
		mavlink/common/mavlink_msg_altitude.h \
		mavlink/common/mavlink_msg_resource_request.h \
		mavlink/common/mavlink_msg_scaled_pressure3.h \
		mavlink/common/mavlink_msg_follow_target.h \
		mavlink/common/mavlink_msg_control_system_state.h \
		mavlink/common/mavlink_msg_battery_status.h \
		mavlink/common/mavlink_msg_autopilot_version.h \
		mavlink/common/mavlink_msg_landing_target.h \
		mavlink/common/mavlink_msg_estimator_status.h \
		mavlink/common/mavlink_msg_wind_cov.h \
		mavlink/common/mavlink_msg_vibration.h \
		mavlink/common/mavlink_msg_home_position.h \
		mavlink/common/mavlink_msg_set_home_position.h \
		mavlink/common/mavlink_msg_message_interval.h \
		mavlink/common/mavlink_msg_extended_sys_state.h \
		mavlink/common/mavlink_msg_adsb_vehicle.h \
		mavlink/common/mavlink_msg_v2_extension.h \
		mavlink/common/mavlink_msg_memory_vect.h \
		mavlink/common/mavlink_msg_debug_vect.h \
		mavlink/common/mavlink_msg_named_value_float.h \
		mavlink/common/mavlink_msg_named_value_int.h \
		mavlink/common/mavlink_msg_statustext.h \
		mavlink/common/mavlink_msg_debug.h \
		mavlink/common_extra_msg/mavlink_msg_cmd_velocity.h \
		mavlink/common_extra_msg/mavlink_msg_cmd_fan_motor_speed.h \
		mavlink/common_extra_msg/mavlink_msg_cmd_worm_motor_speed.h \
		mavlink/common_extra_msg/mavlink_msg_cmd_system.h \
		mavlink/common_extra_msg/mavlink_msg_version.h \
		mavlink/common_extra_msg/mavlink_msg_heart_beat.h \
		mavlink/common_extra_msg/mavlink_msg_imu_data.h \
		mavlink/common_extra_msg/mavlink_msg_odometry_2d.h \
		mavlink/common_extra_msg/mavlink_msg_distance_sensor_data.h \
		mavlink/common_extra_msg/mavlink_msg_mag_sensor.h \
		mavlink/common_extra_msg/mavlink_msg_key.h \
		mavlink/common_extra_msg/mavlink_msg_battery.h \
		mavlink/common_extra_msg/mavlink_msg_time.h \
		mavlink/common_extra_msg/mavlink_msg_sensors_state.h \
		mavlink/common_extra_msg/mavlink_msg_bug_motor_state.h \
		mavlink/common_extra_msg/mavlink_msg_motor_fg.h \
		mavlink/common_extra_msg/mavlink_msg_bug_adc_infra.h \
		mavlink/common_extra_msg/mavlink_msg_led_control.h \
		mavlink/common_extra_msg/mavlink_msg_hardware_error.h \
		mavlink/common_extra_msg/mavlink_msg_cmd_imu.h \
		mavlink/common_extra_msg/mavlink_msg_r16checklist.h \
		mavlink/common_extra_msg/mavlink_msg_startr16test.h \
		mavlink/common_extra_msg/mavlink_msg_vl6180calibration.h \
		mavlink/common_extra_msg/mavlink_msg_pcbachecklist.h \
		mavlink/common_extra_msg/mavlink_msg_test_item_setting.h \
		mavlink/common_extra_msg/mavlink_msg_test_running.h \
		mavlink/common_extra_msg/mavlink_msg_test_reporting.h \
		mavlink/common_extra_msg/mavlink_msg_test_going_on.h \
		mav_udp.h \
		led.h \
		uart_rf433.h \
		uart_robot.h \
		TestResult.h \
		ui_dialog_test_result.h \
		xml.h \
		mainwindow.h
	/usr/lib/x86_64-linux-gnu/qt5/bin/moc $(DEFINES) -I/usr/lib/x86_64-linux-gnu/qt5/mkspecs/linux-g++-64 -I/home/mango/myQT/TestConsole1.1 -I/home/mango/myQT/TestConsole1.1/mavlink -I/usr/include/x86_64-linux-gnu/qt5 -I/usr/include/x86_64-linux-gnu/qt5/QtWidgets -I/usr/include/x86_64-linux-gnu/qt5/QtWebKit -I/usr/include/x86_64-linux-gnu/qt5/QtGui -I/usr/include/x86_64-linux-gnu/qt5/QtNetwork -I/usr/include/x86_64-linux-gnu/qt5/QtXml -I/usr/include/x86_64-linux-gnu/qt5/QtSerialPort -I/usr/include/x86_64-linux-gnu/qt5/QtCore -I/usr/include/c++/5 -I/usr/include/x86_64-linux-gnu/c++/5 -I/usr/include/c++/5/backward -I/usr/lib/gcc/x86_64-linux-gnu/5/include -I/usr/local/include -I/usr/lib/gcc/x86_64-linux-gnu/5/include-fixed -I/usr/include/x86_64-linux-gnu -I/usr/include mainwindow.h -o moc_mainwindow.cpp

moc_led.cpp: led.h
	/usr/lib/x86_64-linux-gnu/qt5/bin/moc $(DEFINES) -I/usr/lib/x86_64-linux-gnu/qt5/mkspecs/linux-g++-64 -I/home/mango/myQT/TestConsole1.1 -I/home/mango/myQT/TestConsole1.1/mavlink -I/usr/include/x86_64-linux-gnu/qt5 -I/usr/include/x86_64-linux-gnu/qt5/QtWidgets -I/usr/include/x86_64-linux-gnu/qt5/QtWebKit -I/usr/include/x86_64-linux-gnu/qt5/QtGui -I/usr/include/x86_64-linux-gnu/qt5/QtNetwork -I/usr/include/x86_64-linux-gnu/qt5/QtXml -I/usr/include/x86_64-linux-gnu/qt5/QtSerialPort -I/usr/include/x86_64-linux-gnu/qt5/QtCore -I/usr/include/c++/5 -I/usr/include/x86_64-linux-gnu/c++/5 -I/usr/include/c++/5/backward -I/usr/lib/gcc/x86_64-linux-gnu/5/include -I/usr/local/include -I/usr/lib/gcc/x86_64-linux-gnu/5/include-fixed -I/usr/include/x86_64-linux-gnu -I/usr/include led.h -o moc_led.cpp

moc_mav.cpp: mavlink/common_extra_msg/mavlink.h \
		mavlink/common_extra_msg/version.h \
		mavlink/common_extra_msg/common_extra_msg.h \
		mavlink/protocol.h \
		mavlink/mavlink_types.h \
		mavlink/mavlink_helpers.h \
		mavlink/checksum.h \
		mavlink/mavlink_conversions.h \
		mavlink/common/common.h \
		mavlink/common/mavlink_msg_heartbeat.h \
		mavlink/common/mavlink_msg_sys_status.h \
		mavlink/common/mavlink_msg_system_time.h \
		mavlink/common/mavlink_msg_ping.h \
		mavlink/common/mavlink_msg_change_operator_control.h \
		mavlink/common/mavlink_msg_change_operator_control_ack.h \
		mavlink/common/mavlink_msg_auth_key.h \
		mavlink/common/mavlink_msg_set_mode.h \
		mavlink/common/mavlink_msg_param_request_read.h \
		mavlink/common/mavlink_msg_param_request_list.h \
		mavlink/common/mavlink_msg_param_value.h \
		mavlink/common/mavlink_msg_param_set.h \
		mavlink/common/mavlink_msg_gps_raw_int.h \
		mavlink/common/mavlink_msg_gps_status.h \
		mavlink/common/mavlink_msg_scaled_imu.h \
		mavlink/common/mavlink_msg_raw_imu.h \
		mavlink/common/mavlink_msg_raw_pressure.h \
		mavlink/common/mavlink_msg_scaled_pressure.h \
		mavlink/common/mavlink_msg_attitude.h \
		mavlink/common/mavlink_msg_attitude_quaternion.h \
		mavlink/common/mavlink_msg_local_position_ned.h \
		mavlink/common/mavlink_msg_global_position_int.h \
		mavlink/common/mavlink_msg_rc_channels_scaled.h \
		mavlink/common/mavlink_msg_rc_channels_raw.h \
		mavlink/common/mavlink_msg_servo_output_raw.h \
		mavlink/common/mavlink_msg_mission_request_partial_list.h \
		mavlink/common/mavlink_msg_mission_write_partial_list.h \
		mavlink/common/mavlink_msg_mission_item.h \
		mavlink/common/mavlink_msg_mission_request.h \
		mavlink/common/mavlink_msg_mission_set_current.h \
		mavlink/common/mavlink_msg_mission_current.h \
		mavlink/common/mavlink_msg_mission_request_list.h \
		mavlink/common/mavlink_msg_mission_count.h \
		mavlink/common/mavlink_msg_mission_clear_all.h \
		mavlink/common/mavlink_msg_mission_item_reached.h \
		mavlink/common/mavlink_msg_mission_ack.h \
		mavlink/common/mavlink_msg_set_gps_global_origin.h \
		mavlink/common/mavlink_msg_gps_global_origin.h \
		mavlink/common/mavlink_msg_param_map_rc.h \
		mavlink/common/mavlink_msg_mission_request_int.h \
		mavlink/common/mavlink_msg_safety_set_allowed_area.h \
		mavlink/common/mavlink_msg_safety_allowed_area.h \
		mavlink/common/mavlink_msg_attitude_quaternion_cov.h \
		mavlink/common/mavlink_msg_nav_controller_output.h \
		mavlink/common/mavlink_msg_global_position_int_cov.h \
		mavlink/common/mavlink_msg_local_position_ned_cov.h \
		mavlink/common/mavlink_msg_rc_channels.h \
		mavlink/common/mavlink_msg_request_data_stream.h \
		mavlink/common/mavlink_msg_data_stream.h \
		mavlink/common/mavlink_msg_manual_control.h \
		mavlink/common/mavlink_msg_rc_channels_override.h \
		mavlink/common/mavlink_msg_mission_item_int.h \
		mavlink/common/mavlink_msg_vfr_hud.h \
		mavlink/common/mavlink_msg_command_int.h \
		mavlink/common/mavlink_msg_command_long.h \
		mavlink/common/mavlink_msg_command_ack.h \
		mavlink/common/mavlink_msg_manual_setpoint.h \
		mavlink/common/mavlink_msg_set_attitude_target.h \
		mavlink/common/mavlink_msg_attitude_target.h \
		mavlink/common/mavlink_msg_set_position_target_local_ned.h \
		mavlink/common/mavlink_msg_position_target_local_ned.h \
		mavlink/common/mavlink_msg_set_position_target_global_int.h \
		mavlink/common/mavlink_msg_position_target_global_int.h \
		mavlink/common/mavlink_msg_local_position_ned_system_global_offset.h \
		mavlink/common/mavlink_msg_hil_state.h \
		mavlink/common/mavlink_msg_hil_controls.h \
		mavlink/common/mavlink_msg_hil_rc_inputs_raw.h \
		mavlink/common/mavlink_msg_optical_flow.h \
		mavlink/common/mavlink_msg_global_vision_position_estimate.h \
		mavlink/common/mavlink_msg_vision_position_estimate.h \
		mavlink/common/mavlink_msg_vision_speed_estimate.h \
		mavlink/common/mavlink_msg_vicon_position_estimate.h \
		mavlink/common/mavlink_msg_highres_imu.h \
		mavlink/common/mavlink_msg_optical_flow_rad.h \
		mavlink/common/mavlink_msg_hil_sensor.h \
		mavlink/common/mavlink_msg_sim_state.h \
		mavlink/common/mavlink_msg_radio_status.h \
		mavlink/common/mavlink_msg_file_transfer_protocol.h \
		mavlink/common/mavlink_msg_timesync.h \
		mavlink/common/mavlink_msg_camera_trigger.h \
		mavlink/common/mavlink_msg_hil_gps.h \
		mavlink/common/mavlink_msg_hil_optical_flow.h \
		mavlink/common/mavlink_msg_hil_state_quaternion.h \
		mavlink/common/mavlink_msg_scaled_imu2.h \
		mavlink/common/mavlink_msg_log_request_list.h \
		mavlink/common/mavlink_msg_log_entry.h \
		mavlink/common/mavlink_msg_log_request_data.h \
		mavlink/common/mavlink_msg_log_data.h \
		mavlink/common/mavlink_msg_log_erase.h \
		mavlink/common/mavlink_msg_log_request_end.h \
		mavlink/common/mavlink_msg_gps_inject_data.h \
		mavlink/common/mavlink_msg_gps2_raw.h \
		mavlink/common/mavlink_msg_power_status.h \
		mavlink/common/mavlink_msg_serial_control.h \
		mavlink/common/mavlink_msg_gps_rtk.h \
		mavlink/common/mavlink_msg_gps2_rtk.h \
		mavlink/common/mavlink_msg_scaled_imu3.h \
		mavlink/common/mavlink_msg_data_transmission_handshake.h \
		mavlink/common/mavlink_msg_encapsulated_data.h \
		mavlink/common/mavlink_msg_distance_sensor.h \
		mavlink/common/mavlink_msg_terrain_request.h \
		mavlink/common/mavlink_msg_terrain_data.h \
		mavlink/common/mavlink_msg_terrain_check.h \
		mavlink/common/mavlink_msg_terrain_report.h \
		mavlink/common/mavlink_msg_scaled_pressure2.h \
		mavlink/common/mavlink_msg_att_pos_mocap.h \
		mavlink/common/mavlink_msg_set_actuator_control_target.h \
		mavlink/common/mavlink_msg_actuator_control_target.h \
		mavlink/common/mavlink_msg_altitude.h \
		mavlink/common/mavlink_msg_resource_request.h \
		mavlink/common/mavlink_msg_scaled_pressure3.h \
		mavlink/common/mavlink_msg_follow_target.h \
		mavlink/common/mavlink_msg_control_system_state.h \
		mavlink/common/mavlink_msg_battery_status.h \
		mavlink/common/mavlink_msg_autopilot_version.h \
		mavlink/common/mavlink_msg_landing_target.h \
		mavlink/common/mavlink_msg_estimator_status.h \
		mavlink/common/mavlink_msg_wind_cov.h \
		mavlink/common/mavlink_msg_vibration.h \
		mavlink/common/mavlink_msg_home_position.h \
		mavlink/common/mavlink_msg_set_home_position.h \
		mavlink/common/mavlink_msg_message_interval.h \
		mavlink/common/mavlink_msg_extended_sys_state.h \
		mavlink/common/mavlink_msg_adsb_vehicle.h \
		mavlink/common/mavlink_msg_v2_extension.h \
		mavlink/common/mavlink_msg_memory_vect.h \
		mavlink/common/mavlink_msg_debug_vect.h \
		mavlink/common/mavlink_msg_named_value_float.h \
		mavlink/common/mavlink_msg_named_value_int.h \
		mavlink/common/mavlink_msg_statustext.h \
		mavlink/common/mavlink_msg_debug.h \
		mavlink/common_extra_msg/mavlink_msg_cmd_velocity.h \
		mavlink/common_extra_msg/mavlink_msg_cmd_fan_motor_speed.h \
		mavlink/common_extra_msg/mavlink_msg_cmd_worm_motor_speed.h \
		mavlink/common_extra_msg/mavlink_msg_cmd_system.h \
		mavlink/common_extra_msg/mavlink_msg_version.h \
		mavlink/common_extra_msg/mavlink_msg_heart_beat.h \
		mavlink/common_extra_msg/mavlink_msg_imu_data.h \
		mavlink/common_extra_msg/mavlink_msg_odometry_2d.h \
		mavlink/common_extra_msg/mavlink_msg_distance_sensor_data.h \
		mavlink/common_extra_msg/mavlink_msg_mag_sensor.h \
		mavlink/common_extra_msg/mavlink_msg_key.h \
		mavlink/common_extra_msg/mavlink_msg_battery.h \
		mavlink/common_extra_msg/mavlink_msg_time.h \
		mavlink/common_extra_msg/mavlink_msg_sensors_state.h \
		mavlink/common_extra_msg/mavlink_msg_bug_motor_state.h \
		mavlink/common_extra_msg/mavlink_msg_motor_fg.h \
		mavlink/common_extra_msg/mavlink_msg_bug_adc_infra.h \
		mavlink/common_extra_msg/mavlink_msg_led_control.h \
		mavlink/common_extra_msg/mavlink_msg_hardware_error.h \
		mavlink/common_extra_msg/mavlink_msg_cmd_imu.h \
		mavlink/common_extra_msg/mavlink_msg_r16checklist.h \
		mavlink/common_extra_msg/mavlink_msg_startr16test.h \
		mavlink/common_extra_msg/mavlink_msg_vl6180calibration.h \
		mavlink/common_extra_msg/mavlink_msg_pcbachecklist.h \
		mavlink/common_extra_msg/mavlink_msg_test_item_setting.h \
		mavlink/common_extra_msg/mavlink_msg_test_running.h \
		mavlink/common_extra_msg/mavlink_msg_test_reporting.h \
		mavlink/common_extra_msg/mavlink_msg_test_going_on.h \
		mav.h
	/usr/lib/x86_64-linux-gnu/qt5/bin/moc $(DEFINES) -I/usr/lib/x86_64-linux-gnu/qt5/mkspecs/linux-g++-64 -I/home/mango/myQT/TestConsole1.1 -I/home/mango/myQT/TestConsole1.1/mavlink -I/usr/include/x86_64-linux-gnu/qt5 -I/usr/include/x86_64-linux-gnu/qt5/QtWidgets -I/usr/include/x86_64-linux-gnu/qt5/QtWebKit -I/usr/include/x86_64-linux-gnu/qt5/QtGui -I/usr/include/x86_64-linux-gnu/qt5/QtNetwork -I/usr/include/x86_64-linux-gnu/qt5/QtXml -I/usr/include/x86_64-linux-gnu/qt5/QtSerialPort -I/usr/include/x86_64-linux-gnu/qt5/QtCore -I/usr/include/c++/5 -I/usr/include/x86_64-linux-gnu/c++/5 -I/usr/include/c++/5/backward -I/usr/lib/gcc/x86_64-linux-gnu/5/include -I/usr/local/include -I/usr/lib/gcc/x86_64-linux-gnu/5/include-fixed -I/usr/include/x86_64-linux-gnu -I/usr/include mav.h -o moc_mav.cpp

moc_mav_udp.cpp: mavlink/common_extra_msg/mavlink.h \
		mavlink/common_extra_msg/version.h \
		mavlink/common_extra_msg/common_extra_msg.h \
		mavlink/protocol.h \
		mavlink/mavlink_types.h \
		mavlink/mavlink_helpers.h \
		mavlink/checksum.h \
		mavlink/mavlink_conversions.h \
		mavlink/common/common.h \
		mavlink/common/mavlink_msg_heartbeat.h \
		mavlink/common/mavlink_msg_sys_status.h \
		mavlink/common/mavlink_msg_system_time.h \
		mavlink/common/mavlink_msg_ping.h \
		mavlink/common/mavlink_msg_change_operator_control.h \
		mavlink/common/mavlink_msg_change_operator_control_ack.h \
		mavlink/common/mavlink_msg_auth_key.h \
		mavlink/common/mavlink_msg_set_mode.h \
		mavlink/common/mavlink_msg_param_request_read.h \
		mavlink/common/mavlink_msg_param_request_list.h \
		mavlink/common/mavlink_msg_param_value.h \
		mavlink/common/mavlink_msg_param_set.h \
		mavlink/common/mavlink_msg_gps_raw_int.h \
		mavlink/common/mavlink_msg_gps_status.h \
		mavlink/common/mavlink_msg_scaled_imu.h \
		mavlink/common/mavlink_msg_raw_imu.h \
		mavlink/common/mavlink_msg_raw_pressure.h \
		mavlink/common/mavlink_msg_scaled_pressure.h \
		mavlink/common/mavlink_msg_attitude.h \
		mavlink/common/mavlink_msg_attitude_quaternion.h \
		mavlink/common/mavlink_msg_local_position_ned.h \
		mavlink/common/mavlink_msg_global_position_int.h \
		mavlink/common/mavlink_msg_rc_channels_scaled.h \
		mavlink/common/mavlink_msg_rc_channels_raw.h \
		mavlink/common/mavlink_msg_servo_output_raw.h \
		mavlink/common/mavlink_msg_mission_request_partial_list.h \
		mavlink/common/mavlink_msg_mission_write_partial_list.h \
		mavlink/common/mavlink_msg_mission_item.h \
		mavlink/common/mavlink_msg_mission_request.h \
		mavlink/common/mavlink_msg_mission_set_current.h \
		mavlink/common/mavlink_msg_mission_current.h \
		mavlink/common/mavlink_msg_mission_request_list.h \
		mavlink/common/mavlink_msg_mission_count.h \
		mavlink/common/mavlink_msg_mission_clear_all.h \
		mavlink/common/mavlink_msg_mission_item_reached.h \
		mavlink/common/mavlink_msg_mission_ack.h \
		mavlink/common/mavlink_msg_set_gps_global_origin.h \
		mavlink/common/mavlink_msg_gps_global_origin.h \
		mavlink/common/mavlink_msg_param_map_rc.h \
		mavlink/common/mavlink_msg_mission_request_int.h \
		mavlink/common/mavlink_msg_safety_set_allowed_area.h \
		mavlink/common/mavlink_msg_safety_allowed_area.h \
		mavlink/common/mavlink_msg_attitude_quaternion_cov.h \
		mavlink/common/mavlink_msg_nav_controller_output.h \
		mavlink/common/mavlink_msg_global_position_int_cov.h \
		mavlink/common/mavlink_msg_local_position_ned_cov.h \
		mavlink/common/mavlink_msg_rc_channels.h \
		mavlink/common/mavlink_msg_request_data_stream.h \
		mavlink/common/mavlink_msg_data_stream.h \
		mavlink/common/mavlink_msg_manual_control.h \
		mavlink/common/mavlink_msg_rc_channels_override.h \
		mavlink/common/mavlink_msg_mission_item_int.h \
		mavlink/common/mavlink_msg_vfr_hud.h \
		mavlink/common/mavlink_msg_command_int.h \
		mavlink/common/mavlink_msg_command_long.h \
		mavlink/common/mavlink_msg_command_ack.h \
		mavlink/common/mavlink_msg_manual_setpoint.h \
		mavlink/common/mavlink_msg_set_attitude_target.h \
		mavlink/common/mavlink_msg_attitude_target.h \
		mavlink/common/mavlink_msg_set_position_target_local_ned.h \
		mavlink/common/mavlink_msg_position_target_local_ned.h \
		mavlink/common/mavlink_msg_set_position_target_global_int.h \
		mavlink/common/mavlink_msg_position_target_global_int.h \
		mavlink/common/mavlink_msg_local_position_ned_system_global_offset.h \
		mavlink/common/mavlink_msg_hil_state.h \
		mavlink/common/mavlink_msg_hil_controls.h \
		mavlink/common/mavlink_msg_hil_rc_inputs_raw.h \
		mavlink/common/mavlink_msg_optical_flow.h \
		mavlink/common/mavlink_msg_global_vision_position_estimate.h \
		mavlink/common/mavlink_msg_vision_position_estimate.h \
		mavlink/common/mavlink_msg_vision_speed_estimate.h \
		mavlink/common/mavlink_msg_vicon_position_estimate.h \
		mavlink/common/mavlink_msg_highres_imu.h \
		mavlink/common/mavlink_msg_optical_flow_rad.h \
		mavlink/common/mavlink_msg_hil_sensor.h \
		mavlink/common/mavlink_msg_sim_state.h \
		mavlink/common/mavlink_msg_radio_status.h \
		mavlink/common/mavlink_msg_file_transfer_protocol.h \
		mavlink/common/mavlink_msg_timesync.h \
		mavlink/common/mavlink_msg_camera_trigger.h \
		mavlink/common/mavlink_msg_hil_gps.h \
		mavlink/common/mavlink_msg_hil_optical_flow.h \
		mavlink/common/mavlink_msg_hil_state_quaternion.h \
		mavlink/common/mavlink_msg_scaled_imu2.h \
		mavlink/common/mavlink_msg_log_request_list.h \
		mavlink/common/mavlink_msg_log_entry.h \
		mavlink/common/mavlink_msg_log_request_data.h \
		mavlink/common/mavlink_msg_log_data.h \
		mavlink/common/mavlink_msg_log_erase.h \
		mavlink/common/mavlink_msg_log_request_end.h \
		mavlink/common/mavlink_msg_gps_inject_data.h \
		mavlink/common/mavlink_msg_gps2_raw.h \
		mavlink/common/mavlink_msg_power_status.h \
		mavlink/common/mavlink_msg_serial_control.h \
		mavlink/common/mavlink_msg_gps_rtk.h \
		mavlink/common/mavlink_msg_gps2_rtk.h \
		mavlink/common/mavlink_msg_scaled_imu3.h \
		mavlink/common/mavlink_msg_data_transmission_handshake.h \
		mavlink/common/mavlink_msg_encapsulated_data.h \
		mavlink/common/mavlink_msg_distance_sensor.h \
		mavlink/common/mavlink_msg_terrain_request.h \
		mavlink/common/mavlink_msg_terrain_data.h \
		mavlink/common/mavlink_msg_terrain_check.h \
		mavlink/common/mavlink_msg_terrain_report.h \
		mavlink/common/mavlink_msg_scaled_pressure2.h \
		mavlink/common/mavlink_msg_att_pos_mocap.h \
		mavlink/common/mavlink_msg_set_actuator_control_target.h \
		mavlink/common/mavlink_msg_actuator_control_target.h \
		mavlink/common/mavlink_msg_altitude.h \
		mavlink/common/mavlink_msg_resource_request.h \
		mavlink/common/mavlink_msg_scaled_pressure3.h \
		mavlink/common/mavlink_msg_follow_target.h \
		mavlink/common/mavlink_msg_control_system_state.h \
		mavlink/common/mavlink_msg_battery_status.h \
		mavlink/common/mavlink_msg_autopilot_version.h \
		mavlink/common/mavlink_msg_landing_target.h \
		mavlink/common/mavlink_msg_estimator_status.h \
		mavlink/common/mavlink_msg_wind_cov.h \
		mavlink/common/mavlink_msg_vibration.h \
		mavlink/common/mavlink_msg_home_position.h \
		mavlink/common/mavlink_msg_set_home_position.h \
		mavlink/common/mavlink_msg_message_interval.h \
		mavlink/common/mavlink_msg_extended_sys_state.h \
		mavlink/common/mavlink_msg_adsb_vehicle.h \
		mavlink/common/mavlink_msg_v2_extension.h \
		mavlink/common/mavlink_msg_memory_vect.h \
		mavlink/common/mavlink_msg_debug_vect.h \
		mavlink/common/mavlink_msg_named_value_float.h \
		mavlink/common/mavlink_msg_named_value_int.h \
		mavlink/common/mavlink_msg_statustext.h \
		mavlink/common/mavlink_msg_debug.h \
		mavlink/common_extra_msg/mavlink_msg_cmd_velocity.h \
		mavlink/common_extra_msg/mavlink_msg_cmd_fan_motor_speed.h \
		mavlink/common_extra_msg/mavlink_msg_cmd_worm_motor_speed.h \
		mavlink/common_extra_msg/mavlink_msg_cmd_system.h \
		mavlink/common_extra_msg/mavlink_msg_version.h \
		mavlink/common_extra_msg/mavlink_msg_heart_beat.h \
		mavlink/common_extra_msg/mavlink_msg_imu_data.h \
		mavlink/common_extra_msg/mavlink_msg_odometry_2d.h \
		mavlink/common_extra_msg/mavlink_msg_distance_sensor_data.h \
		mavlink/common_extra_msg/mavlink_msg_mag_sensor.h \
		mavlink/common_extra_msg/mavlink_msg_key.h \
		mavlink/common_extra_msg/mavlink_msg_battery.h \
		mavlink/common_extra_msg/mavlink_msg_time.h \
		mavlink/common_extra_msg/mavlink_msg_sensors_state.h \
		mavlink/common_extra_msg/mavlink_msg_bug_motor_state.h \
		mavlink/common_extra_msg/mavlink_msg_motor_fg.h \
		mavlink/common_extra_msg/mavlink_msg_bug_adc_infra.h \
		mavlink/common_extra_msg/mavlink_msg_led_control.h \
		mavlink/common_extra_msg/mavlink_msg_hardware_error.h \
		mavlink/common_extra_msg/mavlink_msg_cmd_imu.h \
		mavlink/common_extra_msg/mavlink_msg_r16checklist.h \
		mavlink/common_extra_msg/mavlink_msg_startr16test.h \
		mavlink/common_extra_msg/mavlink_msg_vl6180calibration.h \
		mavlink/common_extra_msg/mavlink_msg_pcbachecklist.h \
		mavlink/common_extra_msg/mavlink_msg_test_item_setting.h \
		mavlink/common_extra_msg/mavlink_msg_test_running.h \
		mavlink/common_extra_msg/mavlink_msg_test_reporting.h \
		mavlink/common_extra_msg/mavlink_msg_test_going_on.h \
		mav_udp.h
	/usr/lib/x86_64-linux-gnu/qt5/bin/moc $(DEFINES) -I/usr/lib/x86_64-linux-gnu/qt5/mkspecs/linux-g++-64 -I/home/mango/myQT/TestConsole1.1 -I/home/mango/myQT/TestConsole1.1/mavlink -I/usr/include/x86_64-linux-gnu/qt5 -I/usr/include/x86_64-linux-gnu/qt5/QtWidgets -I/usr/include/x86_64-linux-gnu/qt5/QtWebKit -I/usr/include/x86_64-linux-gnu/qt5/QtGui -I/usr/include/x86_64-linux-gnu/qt5/QtNetwork -I/usr/include/x86_64-linux-gnu/qt5/QtXml -I/usr/include/x86_64-linux-gnu/qt5/QtSerialPort -I/usr/include/x86_64-linux-gnu/qt5/QtCore -I/usr/include/c++/5 -I/usr/include/x86_64-linux-gnu/c++/5 -I/usr/include/c++/5/backward -I/usr/lib/gcc/x86_64-linux-gnu/5/include -I/usr/local/include -I/usr/lib/gcc/x86_64-linux-gnu/5/include-fixed -I/usr/include/x86_64-linux-gnu -I/usr/include mav_udp.h -o moc_mav_udp.cpp

moc_uart_robot.cpp: uart_robot.h
	/usr/lib/x86_64-linux-gnu/qt5/bin/moc $(DEFINES) -I/usr/lib/x86_64-linux-gnu/qt5/mkspecs/linux-g++-64 -I/home/mango/myQT/TestConsole1.1 -I/home/mango/myQT/TestConsole1.1/mavlink -I/usr/include/x86_64-linux-gnu/qt5 -I/usr/include/x86_64-linux-gnu/qt5/QtWidgets -I/usr/include/x86_64-linux-gnu/qt5/QtWebKit -I/usr/include/x86_64-linux-gnu/qt5/QtGui -I/usr/include/x86_64-linux-gnu/qt5/QtNetwork -I/usr/include/x86_64-linux-gnu/qt5/QtXml -I/usr/include/x86_64-linux-gnu/qt5/QtSerialPort -I/usr/include/x86_64-linux-gnu/qt5/QtCore -I/usr/include/c++/5 -I/usr/include/x86_64-linux-gnu/c++/5 -I/usr/include/c++/5/backward -I/usr/lib/gcc/x86_64-linux-gnu/5/include -I/usr/local/include -I/usr/lib/gcc/x86_64-linux-gnu/5/include-fixed -I/usr/include/x86_64-linux-gnu -I/usr/include uart_robot.h -o moc_uart_robot.cpp

moc_uart_rf433.cpp: uart_rf433.h
	/usr/lib/x86_64-linux-gnu/qt5/bin/moc $(DEFINES) -I/usr/lib/x86_64-linux-gnu/qt5/mkspecs/linux-g++-64 -I/home/mango/myQT/TestConsole1.1 -I/home/mango/myQT/TestConsole1.1/mavlink -I/usr/include/x86_64-linux-gnu/qt5 -I/usr/include/x86_64-linux-gnu/qt5/QtWidgets -I/usr/include/x86_64-linux-gnu/qt5/QtWebKit -I/usr/include/x86_64-linux-gnu/qt5/QtGui -I/usr/include/x86_64-linux-gnu/qt5/QtNetwork -I/usr/include/x86_64-linux-gnu/qt5/QtXml -I/usr/include/x86_64-linux-gnu/qt5/QtSerialPort -I/usr/include/x86_64-linux-gnu/qt5/QtCore -I/usr/include/c++/5 -I/usr/include/x86_64-linux-gnu/c++/5 -I/usr/include/c++/5/backward -I/usr/lib/gcc/x86_64-linux-gnu/5/include -I/usr/local/include -I/usr/lib/gcc/x86_64-linux-gnu/5/include-fixed -I/usr/include/x86_64-linux-gnu -I/usr/include uart_rf433.h -o moc_uart_rf433.cpp

moc_xml.cpp: xml.h
	/usr/lib/x86_64-linux-gnu/qt5/bin/moc $(DEFINES) -I/usr/lib/x86_64-linux-gnu/qt5/mkspecs/linux-g++-64 -I/home/mango/myQT/TestConsole1.1 -I/home/mango/myQT/TestConsole1.1/mavlink -I/usr/include/x86_64-linux-gnu/qt5 -I/usr/include/x86_64-linux-gnu/qt5/QtWidgets -I/usr/include/x86_64-linux-gnu/qt5/QtWebKit -I/usr/include/x86_64-linux-gnu/qt5/QtGui -I/usr/include/x86_64-linux-gnu/qt5/QtNetwork -I/usr/include/x86_64-linux-gnu/qt5/QtXml -I/usr/include/x86_64-linux-gnu/qt5/QtSerialPort -I/usr/include/x86_64-linux-gnu/qt5/QtCore -I/usr/include/c++/5 -I/usr/include/x86_64-linux-gnu/c++/5 -I/usr/include/c++/5/backward -I/usr/lib/gcc/x86_64-linux-gnu/5/include -I/usr/local/include -I/usr/lib/gcc/x86_64-linux-gnu/5/include-fixed -I/usr/include/x86_64-linux-gnu -I/usr/include xml.h -o moc_xml.cpp

moc_TestResult.cpp: ui_dialog_test_result.h \
		TestResult.h
	/usr/lib/x86_64-linux-gnu/qt5/bin/moc $(DEFINES) -I/usr/lib/x86_64-linux-gnu/qt5/mkspecs/linux-g++-64 -I/home/mango/myQT/TestConsole1.1 -I/home/mango/myQT/TestConsole1.1/mavlink -I/usr/include/x86_64-linux-gnu/qt5 -I/usr/include/x86_64-linux-gnu/qt5/QtWidgets -I/usr/include/x86_64-linux-gnu/qt5/QtWebKit -I/usr/include/x86_64-linux-gnu/qt5/QtGui -I/usr/include/x86_64-linux-gnu/qt5/QtNetwork -I/usr/include/x86_64-linux-gnu/qt5/QtXml -I/usr/include/x86_64-linux-gnu/qt5/QtSerialPort -I/usr/include/x86_64-linux-gnu/qt5/QtCore -I/usr/include/c++/5 -I/usr/include/x86_64-linux-gnu/c++/5 -I/usr/include/c++/5/backward -I/usr/lib/gcc/x86_64-linux-gnu/5/include -I/usr/local/include -I/usr/lib/gcc/x86_64-linux-gnu/5/include-fixed -I/usr/include/x86_64-linux-gnu -I/usr/include TestResult.h -o moc_TestResult.cpp

compiler_moc_source_make_all:
compiler_moc_source_clean:
compiler_uic_make_all: ui_mainwindow.h ui_dialog_test_result.h
compiler_uic_clean:
	-$(DEL_FILE) ui_mainwindow.h ui_dialog_test_result.h
ui_mainwindow.h: mainwindow.ui
	/usr/lib/x86_64-linux-gnu/qt5/bin/uic mainwindow.ui -o ui_mainwindow.h

ui_dialog_test_result.h: dialog_test_result.ui
	/usr/lib/x86_64-linux-gnu/qt5/bin/uic dialog_test_result.ui -o ui_dialog_test_result.h

compiler_yacc_decl_make_all:
compiler_yacc_decl_clean:
compiler_yacc_impl_make_all:
compiler_yacc_impl_clean:
compiler_lex_make_all:
compiler_lex_clean:
compiler_clean: compiler_rcc_clean compiler_moc_header_clean compiler_uic_clean 

####### Compile

main.o: main.cpp mainwindow.h \
		mav.h \
		mavlink/common_extra_msg/mavlink.h \
		mavlink/common_extra_msg/version.h \
		mavlink/common_extra_msg/common_extra_msg.h \
		mavlink/protocol.h \
		mavlink/mavlink_types.h \
		mavlink/mavlink_helpers.h \
		mavlink/checksum.h \
		mavlink/mavlink_conversions.h \
		mavlink/common/common.h \
		mavlink/common/mavlink_msg_heartbeat.h \
		mavlink/common/mavlink_msg_sys_status.h \
		mavlink/common/mavlink_msg_system_time.h \
		mavlink/common/mavlink_msg_ping.h \
		mavlink/common/mavlink_msg_change_operator_control.h \
		mavlink/common/mavlink_msg_change_operator_control_ack.h \
		mavlink/common/mavlink_msg_auth_key.h \
		mavlink/common/mavlink_msg_set_mode.h \
		mavlink/common/mavlink_msg_param_request_read.h \
		mavlink/common/mavlink_msg_param_request_list.h \
		mavlink/common/mavlink_msg_param_value.h \
		mavlink/common/mavlink_msg_param_set.h \
		mavlink/common/mavlink_msg_gps_raw_int.h \
		mavlink/common/mavlink_msg_gps_status.h \
		mavlink/common/mavlink_msg_scaled_imu.h \
		mavlink/common/mavlink_msg_raw_imu.h \
		mavlink/common/mavlink_msg_raw_pressure.h \
		mavlink/common/mavlink_msg_scaled_pressure.h \
		mavlink/common/mavlink_msg_attitude.h \
		mavlink/common/mavlink_msg_attitude_quaternion.h \
		mavlink/common/mavlink_msg_local_position_ned.h \
		mavlink/common/mavlink_msg_global_position_int.h \
		mavlink/common/mavlink_msg_rc_channels_scaled.h \
		mavlink/common/mavlink_msg_rc_channels_raw.h \
		mavlink/common/mavlink_msg_servo_output_raw.h \
		mavlink/common/mavlink_msg_mission_request_partial_list.h \
		mavlink/common/mavlink_msg_mission_write_partial_list.h \
		mavlink/common/mavlink_msg_mission_item.h \
		mavlink/common/mavlink_msg_mission_request.h \
		mavlink/common/mavlink_msg_mission_set_current.h \
		mavlink/common/mavlink_msg_mission_current.h \
		mavlink/common/mavlink_msg_mission_request_list.h \
		mavlink/common/mavlink_msg_mission_count.h \
		mavlink/common/mavlink_msg_mission_clear_all.h \
		mavlink/common/mavlink_msg_mission_item_reached.h \
		mavlink/common/mavlink_msg_mission_ack.h \
		mavlink/common/mavlink_msg_set_gps_global_origin.h \
		mavlink/common/mavlink_msg_gps_global_origin.h \
		mavlink/common/mavlink_msg_param_map_rc.h \
		mavlink/common/mavlink_msg_mission_request_int.h \
		mavlink/common/mavlink_msg_safety_set_allowed_area.h \
		mavlink/common/mavlink_msg_safety_allowed_area.h \
		mavlink/common/mavlink_msg_attitude_quaternion_cov.h \
		mavlink/common/mavlink_msg_nav_controller_output.h \
		mavlink/common/mavlink_msg_global_position_int_cov.h \
		mavlink/common/mavlink_msg_local_position_ned_cov.h \
		mavlink/common/mavlink_msg_rc_channels.h \
		mavlink/common/mavlink_msg_request_data_stream.h \
		mavlink/common/mavlink_msg_data_stream.h \
		mavlink/common/mavlink_msg_manual_control.h \
		mavlink/common/mavlink_msg_rc_channels_override.h \
		mavlink/common/mavlink_msg_mission_item_int.h \
		mavlink/common/mavlink_msg_vfr_hud.h \
		mavlink/common/mavlink_msg_command_int.h \
		mavlink/common/mavlink_msg_command_long.h \
		mavlink/common/mavlink_msg_command_ack.h \
		mavlink/common/mavlink_msg_manual_setpoint.h \
		mavlink/common/mavlink_msg_set_attitude_target.h \
		mavlink/common/mavlink_msg_attitude_target.h \
		mavlink/common/mavlink_msg_set_position_target_local_ned.h \
		mavlink/common/mavlink_msg_position_target_local_ned.h \
		mavlink/common/mavlink_msg_set_position_target_global_int.h \
		mavlink/common/mavlink_msg_position_target_global_int.h \
		mavlink/common/mavlink_msg_local_position_ned_system_global_offset.h \
		mavlink/common/mavlink_msg_hil_state.h \
		mavlink/common/mavlink_msg_hil_controls.h \
		mavlink/common/mavlink_msg_hil_rc_inputs_raw.h \
		mavlink/common/mavlink_msg_optical_flow.h \
		mavlink/common/mavlink_msg_global_vision_position_estimate.h \
		mavlink/common/mavlink_msg_vision_position_estimate.h \
		mavlink/common/mavlink_msg_vision_speed_estimate.h \
		mavlink/common/mavlink_msg_vicon_position_estimate.h \
		mavlink/common/mavlink_msg_highres_imu.h \
		mavlink/common/mavlink_msg_optical_flow_rad.h \
		mavlink/common/mavlink_msg_hil_sensor.h \
		mavlink/common/mavlink_msg_sim_state.h \
		mavlink/common/mavlink_msg_radio_status.h \
		mavlink/common/mavlink_msg_file_transfer_protocol.h \
		mavlink/common/mavlink_msg_timesync.h \
		mavlink/common/mavlink_msg_camera_trigger.h \
		mavlink/common/mavlink_msg_hil_gps.h \
		mavlink/common/mavlink_msg_hil_optical_flow.h \
		mavlink/common/mavlink_msg_hil_state_quaternion.h \
		mavlink/common/mavlink_msg_scaled_imu2.h \
		mavlink/common/mavlink_msg_log_request_list.h \
		mavlink/common/mavlink_msg_log_entry.h \
		mavlink/common/mavlink_msg_log_request_data.h \
		mavlink/common/mavlink_msg_log_data.h \
		mavlink/common/mavlink_msg_log_erase.h \
		mavlink/common/mavlink_msg_log_request_end.h \
		mavlink/common/mavlink_msg_gps_inject_data.h \
		mavlink/common/mavlink_msg_gps2_raw.h \
		mavlink/common/mavlink_msg_power_status.h \
		mavlink/common/mavlink_msg_serial_control.h \
		mavlink/common/mavlink_msg_gps_rtk.h \
		mavlink/common/mavlink_msg_gps2_rtk.h \
		mavlink/common/mavlink_msg_scaled_imu3.h \
		mavlink/common/mavlink_msg_data_transmission_handshake.h \
		mavlink/common/mavlink_msg_encapsulated_data.h \
		mavlink/common/mavlink_msg_distance_sensor.h \
		mavlink/common/mavlink_msg_terrain_request.h \
		mavlink/common/mavlink_msg_terrain_data.h \
		mavlink/common/mavlink_msg_terrain_check.h \
		mavlink/common/mavlink_msg_terrain_report.h \
		mavlink/common/mavlink_msg_scaled_pressure2.h \
		mavlink/common/mavlink_msg_att_pos_mocap.h \
		mavlink/common/mavlink_msg_set_actuator_control_target.h \
		mavlink/common/mavlink_msg_actuator_control_target.h \
		mavlink/common/mavlink_msg_altitude.h \
		mavlink/common/mavlink_msg_resource_request.h \
		mavlink/common/mavlink_msg_scaled_pressure3.h \
		mavlink/common/mavlink_msg_follow_target.h \
		mavlink/common/mavlink_msg_control_system_state.h \
		mavlink/common/mavlink_msg_battery_status.h \
		mavlink/common/mavlink_msg_autopilot_version.h \
		mavlink/common/mavlink_msg_landing_target.h \
		mavlink/common/mavlink_msg_estimator_status.h \
		mavlink/common/mavlink_msg_wind_cov.h \
		mavlink/common/mavlink_msg_vibration.h \
		mavlink/common/mavlink_msg_home_position.h \
		mavlink/common/mavlink_msg_set_home_position.h \
		mavlink/common/mavlink_msg_message_interval.h \
		mavlink/common/mavlink_msg_extended_sys_state.h \
		mavlink/common/mavlink_msg_adsb_vehicle.h \
		mavlink/common/mavlink_msg_v2_extension.h \
		mavlink/common/mavlink_msg_memory_vect.h \
		mavlink/common/mavlink_msg_debug_vect.h \
		mavlink/common/mavlink_msg_named_value_float.h \
		mavlink/common/mavlink_msg_named_value_int.h \
		mavlink/common/mavlink_msg_statustext.h \
		mavlink/common/mavlink_msg_debug.h \
		mavlink/common_extra_msg/mavlink_msg_cmd_velocity.h \
		mavlink/common_extra_msg/mavlink_msg_cmd_fan_motor_speed.h \
		mavlink/common_extra_msg/mavlink_msg_cmd_worm_motor_speed.h \
		mavlink/common_extra_msg/mavlink_msg_cmd_system.h \
		mavlink/common_extra_msg/mavlink_msg_version.h \
		mavlink/common_extra_msg/mavlink_msg_heart_beat.h \
		mavlink/common_extra_msg/mavlink_msg_imu_data.h \
		mavlink/common_extra_msg/mavlink_msg_odometry_2d.h \
		mavlink/common_extra_msg/mavlink_msg_distance_sensor_data.h \
		mavlink/common_extra_msg/mavlink_msg_mag_sensor.h \
		mavlink/common_extra_msg/mavlink_msg_key.h \
		mavlink/common_extra_msg/mavlink_msg_battery.h \
		mavlink/common_extra_msg/mavlink_msg_time.h \
		mavlink/common_extra_msg/mavlink_msg_sensors_state.h \
		mavlink/common_extra_msg/mavlink_msg_bug_motor_state.h \
		mavlink/common_extra_msg/mavlink_msg_motor_fg.h \
		mavlink/common_extra_msg/mavlink_msg_bug_adc_infra.h \
		mavlink/common_extra_msg/mavlink_msg_led_control.h \
		mavlink/common_extra_msg/mavlink_msg_hardware_error.h \
		mavlink/common_extra_msg/mavlink_msg_cmd_imu.h \
		mavlink/common_extra_msg/mavlink_msg_r16checklist.h \
		mavlink/common_extra_msg/mavlink_msg_startr16test.h \
		mavlink/common_extra_msg/mavlink_msg_vl6180calibration.h \
		mavlink/common_extra_msg/mavlink_msg_pcbachecklist.h \
		mavlink/common_extra_msg/mavlink_msg_test_item_setting.h \
		mavlink/common_extra_msg/mavlink_msg_test_running.h \
		mavlink/common_extra_msg/mavlink_msg_test_reporting.h \
		mavlink/common_extra_msg/mavlink_msg_test_going_on.h \
		mav_udp.h \
		led.h \
		uart_rf433.h \
		uart_robot.h \
		TestResult.h \
		ui_dialog_test_result.h \
		xml.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o main.o main.cpp

mainwindow.o: mainwindow.cpp mainwindow.h \
		mav.h \
		mavlink/common_extra_msg/mavlink.h \
		mavlink/common_extra_msg/version.h \
		mavlink/common_extra_msg/common_extra_msg.h \
		mavlink/protocol.h \
		mavlink/mavlink_types.h \
		mavlink/mavlink_helpers.h \
		mavlink/checksum.h \
		mavlink/mavlink_conversions.h \
		mavlink/common/common.h \
		mavlink/common/mavlink_msg_heartbeat.h \
		mavlink/common/mavlink_msg_sys_status.h \
		mavlink/common/mavlink_msg_system_time.h \
		mavlink/common/mavlink_msg_ping.h \
		mavlink/common/mavlink_msg_change_operator_control.h \
		mavlink/common/mavlink_msg_change_operator_control_ack.h \
		mavlink/common/mavlink_msg_auth_key.h \
		mavlink/common/mavlink_msg_set_mode.h \
		mavlink/common/mavlink_msg_param_request_read.h \
		mavlink/common/mavlink_msg_param_request_list.h \
		mavlink/common/mavlink_msg_param_value.h \
		mavlink/common/mavlink_msg_param_set.h \
		mavlink/common/mavlink_msg_gps_raw_int.h \
		mavlink/common/mavlink_msg_gps_status.h \
		mavlink/common/mavlink_msg_scaled_imu.h \
		mavlink/common/mavlink_msg_raw_imu.h \
		mavlink/common/mavlink_msg_raw_pressure.h \
		mavlink/common/mavlink_msg_scaled_pressure.h \
		mavlink/common/mavlink_msg_attitude.h \
		mavlink/common/mavlink_msg_attitude_quaternion.h \
		mavlink/common/mavlink_msg_local_position_ned.h \
		mavlink/common/mavlink_msg_global_position_int.h \
		mavlink/common/mavlink_msg_rc_channels_scaled.h \
		mavlink/common/mavlink_msg_rc_channels_raw.h \
		mavlink/common/mavlink_msg_servo_output_raw.h \
		mavlink/common/mavlink_msg_mission_request_partial_list.h \
		mavlink/common/mavlink_msg_mission_write_partial_list.h \
		mavlink/common/mavlink_msg_mission_item.h \
		mavlink/common/mavlink_msg_mission_request.h \
		mavlink/common/mavlink_msg_mission_set_current.h \
		mavlink/common/mavlink_msg_mission_current.h \
		mavlink/common/mavlink_msg_mission_request_list.h \
		mavlink/common/mavlink_msg_mission_count.h \
		mavlink/common/mavlink_msg_mission_clear_all.h \
		mavlink/common/mavlink_msg_mission_item_reached.h \
		mavlink/common/mavlink_msg_mission_ack.h \
		mavlink/common/mavlink_msg_set_gps_global_origin.h \
		mavlink/common/mavlink_msg_gps_global_origin.h \
		mavlink/common/mavlink_msg_param_map_rc.h \
		mavlink/common/mavlink_msg_mission_request_int.h \
		mavlink/common/mavlink_msg_safety_set_allowed_area.h \
		mavlink/common/mavlink_msg_safety_allowed_area.h \
		mavlink/common/mavlink_msg_attitude_quaternion_cov.h \
		mavlink/common/mavlink_msg_nav_controller_output.h \
		mavlink/common/mavlink_msg_global_position_int_cov.h \
		mavlink/common/mavlink_msg_local_position_ned_cov.h \
		mavlink/common/mavlink_msg_rc_channels.h \
		mavlink/common/mavlink_msg_request_data_stream.h \
		mavlink/common/mavlink_msg_data_stream.h \
		mavlink/common/mavlink_msg_manual_control.h \
		mavlink/common/mavlink_msg_rc_channels_override.h \
		mavlink/common/mavlink_msg_mission_item_int.h \
		mavlink/common/mavlink_msg_vfr_hud.h \
		mavlink/common/mavlink_msg_command_int.h \
		mavlink/common/mavlink_msg_command_long.h \
		mavlink/common/mavlink_msg_command_ack.h \
		mavlink/common/mavlink_msg_manual_setpoint.h \
		mavlink/common/mavlink_msg_set_attitude_target.h \
		mavlink/common/mavlink_msg_attitude_target.h \
		mavlink/common/mavlink_msg_set_position_target_local_ned.h \
		mavlink/common/mavlink_msg_position_target_local_ned.h \
		mavlink/common/mavlink_msg_set_position_target_global_int.h \
		mavlink/common/mavlink_msg_position_target_global_int.h \
		mavlink/common/mavlink_msg_local_position_ned_system_global_offset.h \
		mavlink/common/mavlink_msg_hil_state.h \
		mavlink/common/mavlink_msg_hil_controls.h \
		mavlink/common/mavlink_msg_hil_rc_inputs_raw.h \
		mavlink/common/mavlink_msg_optical_flow.h \
		mavlink/common/mavlink_msg_global_vision_position_estimate.h \
		mavlink/common/mavlink_msg_vision_position_estimate.h \
		mavlink/common/mavlink_msg_vision_speed_estimate.h \
		mavlink/common/mavlink_msg_vicon_position_estimate.h \
		mavlink/common/mavlink_msg_highres_imu.h \
		mavlink/common/mavlink_msg_optical_flow_rad.h \
		mavlink/common/mavlink_msg_hil_sensor.h \
		mavlink/common/mavlink_msg_sim_state.h \
		mavlink/common/mavlink_msg_radio_status.h \
		mavlink/common/mavlink_msg_file_transfer_protocol.h \
		mavlink/common/mavlink_msg_timesync.h \
		mavlink/common/mavlink_msg_camera_trigger.h \
		mavlink/common/mavlink_msg_hil_gps.h \
		mavlink/common/mavlink_msg_hil_optical_flow.h \
		mavlink/common/mavlink_msg_hil_state_quaternion.h \
		mavlink/common/mavlink_msg_scaled_imu2.h \
		mavlink/common/mavlink_msg_log_request_list.h \
		mavlink/common/mavlink_msg_log_entry.h \
		mavlink/common/mavlink_msg_log_request_data.h \
		mavlink/common/mavlink_msg_log_data.h \
		mavlink/common/mavlink_msg_log_erase.h \
		mavlink/common/mavlink_msg_log_request_end.h \
		mavlink/common/mavlink_msg_gps_inject_data.h \
		mavlink/common/mavlink_msg_gps2_raw.h \
		mavlink/common/mavlink_msg_power_status.h \
		mavlink/common/mavlink_msg_serial_control.h \
		mavlink/common/mavlink_msg_gps_rtk.h \
		mavlink/common/mavlink_msg_gps2_rtk.h \
		mavlink/common/mavlink_msg_scaled_imu3.h \
		mavlink/common/mavlink_msg_data_transmission_handshake.h \
		mavlink/common/mavlink_msg_encapsulated_data.h \
		mavlink/common/mavlink_msg_distance_sensor.h \
		mavlink/common/mavlink_msg_terrain_request.h \
		mavlink/common/mavlink_msg_terrain_data.h \
		mavlink/common/mavlink_msg_terrain_check.h \
		mavlink/common/mavlink_msg_terrain_report.h \
		mavlink/common/mavlink_msg_scaled_pressure2.h \
		mavlink/common/mavlink_msg_att_pos_mocap.h \
		mavlink/common/mavlink_msg_set_actuator_control_target.h \
		mavlink/common/mavlink_msg_actuator_control_target.h \
		mavlink/common/mavlink_msg_altitude.h \
		mavlink/common/mavlink_msg_resource_request.h \
		mavlink/common/mavlink_msg_scaled_pressure3.h \
		mavlink/common/mavlink_msg_follow_target.h \
		mavlink/common/mavlink_msg_control_system_state.h \
		mavlink/common/mavlink_msg_battery_status.h \
		mavlink/common/mavlink_msg_autopilot_version.h \
		mavlink/common/mavlink_msg_landing_target.h \
		mavlink/common/mavlink_msg_estimator_status.h \
		mavlink/common/mavlink_msg_wind_cov.h \
		mavlink/common/mavlink_msg_vibration.h \
		mavlink/common/mavlink_msg_home_position.h \
		mavlink/common/mavlink_msg_set_home_position.h \
		mavlink/common/mavlink_msg_message_interval.h \
		mavlink/common/mavlink_msg_extended_sys_state.h \
		mavlink/common/mavlink_msg_adsb_vehicle.h \
		mavlink/common/mavlink_msg_v2_extension.h \
		mavlink/common/mavlink_msg_memory_vect.h \
		mavlink/common/mavlink_msg_debug_vect.h \
		mavlink/common/mavlink_msg_named_value_float.h \
		mavlink/common/mavlink_msg_named_value_int.h \
		mavlink/common/mavlink_msg_statustext.h \
		mavlink/common/mavlink_msg_debug.h \
		mavlink/common_extra_msg/mavlink_msg_cmd_velocity.h \
		mavlink/common_extra_msg/mavlink_msg_cmd_fan_motor_speed.h \
		mavlink/common_extra_msg/mavlink_msg_cmd_worm_motor_speed.h \
		mavlink/common_extra_msg/mavlink_msg_cmd_system.h \
		mavlink/common_extra_msg/mavlink_msg_version.h \
		mavlink/common_extra_msg/mavlink_msg_heart_beat.h \
		mavlink/common_extra_msg/mavlink_msg_imu_data.h \
		mavlink/common_extra_msg/mavlink_msg_odometry_2d.h \
		mavlink/common_extra_msg/mavlink_msg_distance_sensor_data.h \
		mavlink/common_extra_msg/mavlink_msg_mag_sensor.h \
		mavlink/common_extra_msg/mavlink_msg_key.h \
		mavlink/common_extra_msg/mavlink_msg_battery.h \
		mavlink/common_extra_msg/mavlink_msg_time.h \
		mavlink/common_extra_msg/mavlink_msg_sensors_state.h \
		mavlink/common_extra_msg/mavlink_msg_bug_motor_state.h \
		mavlink/common_extra_msg/mavlink_msg_motor_fg.h \
		mavlink/common_extra_msg/mavlink_msg_bug_adc_infra.h \
		mavlink/common_extra_msg/mavlink_msg_led_control.h \
		mavlink/common_extra_msg/mavlink_msg_hardware_error.h \
		mavlink/common_extra_msg/mavlink_msg_cmd_imu.h \
		mavlink/common_extra_msg/mavlink_msg_r16checklist.h \
		mavlink/common_extra_msg/mavlink_msg_startr16test.h \
		mavlink/common_extra_msg/mavlink_msg_vl6180calibration.h \
		mavlink/common_extra_msg/mavlink_msg_pcbachecklist.h \
		mavlink/common_extra_msg/mavlink_msg_test_item_setting.h \
		mavlink/common_extra_msg/mavlink_msg_test_running.h \
		mavlink/common_extra_msg/mavlink_msg_test_reporting.h \
		mavlink/common_extra_msg/mavlink_msg_test_going_on.h \
		mav_udp.h \
		led.h \
		uart_rf433.h \
		uart_robot.h \
		TestResult.h \
		ui_dialog_test_result.h \
		xml.h \
		ui_mainwindow.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o mainwindow.o mainwindow.cpp

led.o: led.cpp led.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o led.o led.cpp

mav.o: mav.cpp mav.h \
		mavlink/common_extra_msg/mavlink.h \
		mavlink/common_extra_msg/version.h \
		mavlink/common_extra_msg/common_extra_msg.h \
		mavlink/protocol.h \
		mavlink/mavlink_types.h \
		mavlink/mavlink_helpers.h \
		mavlink/checksum.h \
		mavlink/mavlink_conversions.h \
		mavlink/common/common.h \
		mavlink/common/mavlink_msg_heartbeat.h \
		mavlink/common/mavlink_msg_sys_status.h \
		mavlink/common/mavlink_msg_system_time.h \
		mavlink/common/mavlink_msg_ping.h \
		mavlink/common/mavlink_msg_change_operator_control.h \
		mavlink/common/mavlink_msg_change_operator_control_ack.h \
		mavlink/common/mavlink_msg_auth_key.h \
		mavlink/common/mavlink_msg_set_mode.h \
		mavlink/common/mavlink_msg_param_request_read.h \
		mavlink/common/mavlink_msg_param_request_list.h \
		mavlink/common/mavlink_msg_param_value.h \
		mavlink/common/mavlink_msg_param_set.h \
		mavlink/common/mavlink_msg_gps_raw_int.h \
		mavlink/common/mavlink_msg_gps_status.h \
		mavlink/common/mavlink_msg_scaled_imu.h \
		mavlink/common/mavlink_msg_raw_imu.h \
		mavlink/common/mavlink_msg_raw_pressure.h \
		mavlink/common/mavlink_msg_scaled_pressure.h \
		mavlink/common/mavlink_msg_attitude.h \
		mavlink/common/mavlink_msg_attitude_quaternion.h \
		mavlink/common/mavlink_msg_local_position_ned.h \
		mavlink/common/mavlink_msg_global_position_int.h \
		mavlink/common/mavlink_msg_rc_channels_scaled.h \
		mavlink/common/mavlink_msg_rc_channels_raw.h \
		mavlink/common/mavlink_msg_servo_output_raw.h \
		mavlink/common/mavlink_msg_mission_request_partial_list.h \
		mavlink/common/mavlink_msg_mission_write_partial_list.h \
		mavlink/common/mavlink_msg_mission_item.h \
		mavlink/common/mavlink_msg_mission_request.h \
		mavlink/common/mavlink_msg_mission_set_current.h \
		mavlink/common/mavlink_msg_mission_current.h \
		mavlink/common/mavlink_msg_mission_request_list.h \
		mavlink/common/mavlink_msg_mission_count.h \
		mavlink/common/mavlink_msg_mission_clear_all.h \
		mavlink/common/mavlink_msg_mission_item_reached.h \
		mavlink/common/mavlink_msg_mission_ack.h \
		mavlink/common/mavlink_msg_set_gps_global_origin.h \
		mavlink/common/mavlink_msg_gps_global_origin.h \
		mavlink/common/mavlink_msg_param_map_rc.h \
		mavlink/common/mavlink_msg_mission_request_int.h \
		mavlink/common/mavlink_msg_safety_set_allowed_area.h \
		mavlink/common/mavlink_msg_safety_allowed_area.h \
		mavlink/common/mavlink_msg_attitude_quaternion_cov.h \
		mavlink/common/mavlink_msg_nav_controller_output.h \
		mavlink/common/mavlink_msg_global_position_int_cov.h \
		mavlink/common/mavlink_msg_local_position_ned_cov.h \
		mavlink/common/mavlink_msg_rc_channels.h \
		mavlink/common/mavlink_msg_request_data_stream.h \
		mavlink/common/mavlink_msg_data_stream.h \
		mavlink/common/mavlink_msg_manual_control.h \
		mavlink/common/mavlink_msg_rc_channels_override.h \
		mavlink/common/mavlink_msg_mission_item_int.h \
		mavlink/common/mavlink_msg_vfr_hud.h \
		mavlink/common/mavlink_msg_command_int.h \
		mavlink/common/mavlink_msg_command_long.h \
		mavlink/common/mavlink_msg_command_ack.h \
		mavlink/common/mavlink_msg_manual_setpoint.h \
		mavlink/common/mavlink_msg_set_attitude_target.h \
		mavlink/common/mavlink_msg_attitude_target.h \
		mavlink/common/mavlink_msg_set_position_target_local_ned.h \
		mavlink/common/mavlink_msg_position_target_local_ned.h \
		mavlink/common/mavlink_msg_set_position_target_global_int.h \
		mavlink/common/mavlink_msg_position_target_global_int.h \
		mavlink/common/mavlink_msg_local_position_ned_system_global_offset.h \
		mavlink/common/mavlink_msg_hil_state.h \
		mavlink/common/mavlink_msg_hil_controls.h \
		mavlink/common/mavlink_msg_hil_rc_inputs_raw.h \
		mavlink/common/mavlink_msg_optical_flow.h \
		mavlink/common/mavlink_msg_global_vision_position_estimate.h \
		mavlink/common/mavlink_msg_vision_position_estimate.h \
		mavlink/common/mavlink_msg_vision_speed_estimate.h \
		mavlink/common/mavlink_msg_vicon_position_estimate.h \
		mavlink/common/mavlink_msg_highres_imu.h \
		mavlink/common/mavlink_msg_optical_flow_rad.h \
		mavlink/common/mavlink_msg_hil_sensor.h \
		mavlink/common/mavlink_msg_sim_state.h \
		mavlink/common/mavlink_msg_radio_status.h \
		mavlink/common/mavlink_msg_file_transfer_protocol.h \
		mavlink/common/mavlink_msg_timesync.h \
		mavlink/common/mavlink_msg_camera_trigger.h \
		mavlink/common/mavlink_msg_hil_gps.h \
		mavlink/common/mavlink_msg_hil_optical_flow.h \
		mavlink/common/mavlink_msg_hil_state_quaternion.h \
		mavlink/common/mavlink_msg_scaled_imu2.h \
		mavlink/common/mavlink_msg_log_request_list.h \
		mavlink/common/mavlink_msg_log_entry.h \
		mavlink/common/mavlink_msg_log_request_data.h \
		mavlink/common/mavlink_msg_log_data.h \
		mavlink/common/mavlink_msg_log_erase.h \
		mavlink/common/mavlink_msg_log_request_end.h \
		mavlink/common/mavlink_msg_gps_inject_data.h \
		mavlink/common/mavlink_msg_gps2_raw.h \
		mavlink/common/mavlink_msg_power_status.h \
		mavlink/common/mavlink_msg_serial_control.h \
		mavlink/common/mavlink_msg_gps_rtk.h \
		mavlink/common/mavlink_msg_gps2_rtk.h \
		mavlink/common/mavlink_msg_scaled_imu3.h \
		mavlink/common/mavlink_msg_data_transmission_handshake.h \
		mavlink/common/mavlink_msg_encapsulated_data.h \
		mavlink/common/mavlink_msg_distance_sensor.h \
		mavlink/common/mavlink_msg_terrain_request.h \
		mavlink/common/mavlink_msg_terrain_data.h \
		mavlink/common/mavlink_msg_terrain_check.h \
		mavlink/common/mavlink_msg_terrain_report.h \
		mavlink/common/mavlink_msg_scaled_pressure2.h \
		mavlink/common/mavlink_msg_att_pos_mocap.h \
		mavlink/common/mavlink_msg_set_actuator_control_target.h \
		mavlink/common/mavlink_msg_actuator_control_target.h \
		mavlink/common/mavlink_msg_altitude.h \
		mavlink/common/mavlink_msg_resource_request.h \
		mavlink/common/mavlink_msg_scaled_pressure3.h \
		mavlink/common/mavlink_msg_follow_target.h \
		mavlink/common/mavlink_msg_control_system_state.h \
		mavlink/common/mavlink_msg_battery_status.h \
		mavlink/common/mavlink_msg_autopilot_version.h \
		mavlink/common/mavlink_msg_landing_target.h \
		mavlink/common/mavlink_msg_estimator_status.h \
		mavlink/common/mavlink_msg_wind_cov.h \
		mavlink/common/mavlink_msg_vibration.h \
		mavlink/common/mavlink_msg_home_position.h \
		mavlink/common/mavlink_msg_set_home_position.h \
		mavlink/common/mavlink_msg_message_interval.h \
		mavlink/common/mavlink_msg_extended_sys_state.h \
		mavlink/common/mavlink_msg_adsb_vehicle.h \
		mavlink/common/mavlink_msg_v2_extension.h \
		mavlink/common/mavlink_msg_memory_vect.h \
		mavlink/common/mavlink_msg_debug_vect.h \
		mavlink/common/mavlink_msg_named_value_float.h \
		mavlink/common/mavlink_msg_named_value_int.h \
		mavlink/common/mavlink_msg_statustext.h \
		mavlink/common/mavlink_msg_debug.h \
		mavlink/common_extra_msg/mavlink_msg_cmd_velocity.h \
		mavlink/common_extra_msg/mavlink_msg_cmd_fan_motor_speed.h \
		mavlink/common_extra_msg/mavlink_msg_cmd_worm_motor_speed.h \
		mavlink/common_extra_msg/mavlink_msg_cmd_system.h \
		mavlink/common_extra_msg/mavlink_msg_version.h \
		mavlink/common_extra_msg/mavlink_msg_heart_beat.h \
		mavlink/common_extra_msg/mavlink_msg_imu_data.h \
		mavlink/common_extra_msg/mavlink_msg_odometry_2d.h \
		mavlink/common_extra_msg/mavlink_msg_distance_sensor_data.h \
		mavlink/common_extra_msg/mavlink_msg_mag_sensor.h \
		mavlink/common_extra_msg/mavlink_msg_key.h \
		mavlink/common_extra_msg/mavlink_msg_battery.h \
		mavlink/common_extra_msg/mavlink_msg_time.h \
		mavlink/common_extra_msg/mavlink_msg_sensors_state.h \
		mavlink/common_extra_msg/mavlink_msg_bug_motor_state.h \
		mavlink/common_extra_msg/mavlink_msg_motor_fg.h \
		mavlink/common_extra_msg/mavlink_msg_bug_adc_infra.h \
		mavlink/common_extra_msg/mavlink_msg_led_control.h \
		mavlink/common_extra_msg/mavlink_msg_hardware_error.h \
		mavlink/common_extra_msg/mavlink_msg_cmd_imu.h \
		mavlink/common_extra_msg/mavlink_msg_r16checklist.h \
		mavlink/common_extra_msg/mavlink_msg_startr16test.h \
		mavlink/common_extra_msg/mavlink_msg_vl6180calibration.h \
		mavlink/common_extra_msg/mavlink_msg_pcbachecklist.h \
		mavlink/common_extra_msg/mavlink_msg_test_item_setting.h \
		mavlink/common_extra_msg/mavlink_msg_test_running.h \
		mavlink/common_extra_msg/mavlink_msg_test_reporting.h \
		mavlink/common_extra_msg/mavlink_msg_test_going_on.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o mav.o mav.cpp

mav_udp.o: mav_udp.cpp mav_udp.h \
		mavlink/common_extra_msg/mavlink.h \
		mavlink/common_extra_msg/version.h \
		mavlink/common_extra_msg/common_extra_msg.h \
		mavlink/protocol.h \
		mavlink/mavlink_types.h \
		mavlink/mavlink_helpers.h \
		mavlink/checksum.h \
		mavlink/mavlink_conversions.h \
		mavlink/common/common.h \
		mavlink/common/mavlink_msg_heartbeat.h \
		mavlink/common/mavlink_msg_sys_status.h \
		mavlink/common/mavlink_msg_system_time.h \
		mavlink/common/mavlink_msg_ping.h \
		mavlink/common/mavlink_msg_change_operator_control.h \
		mavlink/common/mavlink_msg_change_operator_control_ack.h \
		mavlink/common/mavlink_msg_auth_key.h \
		mavlink/common/mavlink_msg_set_mode.h \
		mavlink/common/mavlink_msg_param_request_read.h \
		mavlink/common/mavlink_msg_param_request_list.h \
		mavlink/common/mavlink_msg_param_value.h \
		mavlink/common/mavlink_msg_param_set.h \
		mavlink/common/mavlink_msg_gps_raw_int.h \
		mavlink/common/mavlink_msg_gps_status.h \
		mavlink/common/mavlink_msg_scaled_imu.h \
		mavlink/common/mavlink_msg_raw_imu.h \
		mavlink/common/mavlink_msg_raw_pressure.h \
		mavlink/common/mavlink_msg_scaled_pressure.h \
		mavlink/common/mavlink_msg_attitude.h \
		mavlink/common/mavlink_msg_attitude_quaternion.h \
		mavlink/common/mavlink_msg_local_position_ned.h \
		mavlink/common/mavlink_msg_global_position_int.h \
		mavlink/common/mavlink_msg_rc_channels_scaled.h \
		mavlink/common/mavlink_msg_rc_channels_raw.h \
		mavlink/common/mavlink_msg_servo_output_raw.h \
		mavlink/common/mavlink_msg_mission_request_partial_list.h \
		mavlink/common/mavlink_msg_mission_write_partial_list.h \
		mavlink/common/mavlink_msg_mission_item.h \
		mavlink/common/mavlink_msg_mission_request.h \
		mavlink/common/mavlink_msg_mission_set_current.h \
		mavlink/common/mavlink_msg_mission_current.h \
		mavlink/common/mavlink_msg_mission_request_list.h \
		mavlink/common/mavlink_msg_mission_count.h \
		mavlink/common/mavlink_msg_mission_clear_all.h \
		mavlink/common/mavlink_msg_mission_item_reached.h \
		mavlink/common/mavlink_msg_mission_ack.h \
		mavlink/common/mavlink_msg_set_gps_global_origin.h \
		mavlink/common/mavlink_msg_gps_global_origin.h \
		mavlink/common/mavlink_msg_param_map_rc.h \
		mavlink/common/mavlink_msg_mission_request_int.h \
		mavlink/common/mavlink_msg_safety_set_allowed_area.h \
		mavlink/common/mavlink_msg_safety_allowed_area.h \
		mavlink/common/mavlink_msg_attitude_quaternion_cov.h \
		mavlink/common/mavlink_msg_nav_controller_output.h \
		mavlink/common/mavlink_msg_global_position_int_cov.h \
		mavlink/common/mavlink_msg_local_position_ned_cov.h \
		mavlink/common/mavlink_msg_rc_channels.h \
		mavlink/common/mavlink_msg_request_data_stream.h \
		mavlink/common/mavlink_msg_data_stream.h \
		mavlink/common/mavlink_msg_manual_control.h \
		mavlink/common/mavlink_msg_rc_channels_override.h \
		mavlink/common/mavlink_msg_mission_item_int.h \
		mavlink/common/mavlink_msg_vfr_hud.h \
		mavlink/common/mavlink_msg_command_int.h \
		mavlink/common/mavlink_msg_command_long.h \
		mavlink/common/mavlink_msg_command_ack.h \
		mavlink/common/mavlink_msg_manual_setpoint.h \
		mavlink/common/mavlink_msg_set_attitude_target.h \
		mavlink/common/mavlink_msg_attitude_target.h \
		mavlink/common/mavlink_msg_set_position_target_local_ned.h \
		mavlink/common/mavlink_msg_position_target_local_ned.h \
		mavlink/common/mavlink_msg_set_position_target_global_int.h \
		mavlink/common/mavlink_msg_position_target_global_int.h \
		mavlink/common/mavlink_msg_local_position_ned_system_global_offset.h \
		mavlink/common/mavlink_msg_hil_state.h \
		mavlink/common/mavlink_msg_hil_controls.h \
		mavlink/common/mavlink_msg_hil_rc_inputs_raw.h \
		mavlink/common/mavlink_msg_optical_flow.h \
		mavlink/common/mavlink_msg_global_vision_position_estimate.h \
		mavlink/common/mavlink_msg_vision_position_estimate.h \
		mavlink/common/mavlink_msg_vision_speed_estimate.h \
		mavlink/common/mavlink_msg_vicon_position_estimate.h \
		mavlink/common/mavlink_msg_highres_imu.h \
		mavlink/common/mavlink_msg_optical_flow_rad.h \
		mavlink/common/mavlink_msg_hil_sensor.h \
		mavlink/common/mavlink_msg_sim_state.h \
		mavlink/common/mavlink_msg_radio_status.h \
		mavlink/common/mavlink_msg_file_transfer_protocol.h \
		mavlink/common/mavlink_msg_timesync.h \
		mavlink/common/mavlink_msg_camera_trigger.h \
		mavlink/common/mavlink_msg_hil_gps.h \
		mavlink/common/mavlink_msg_hil_optical_flow.h \
		mavlink/common/mavlink_msg_hil_state_quaternion.h \
		mavlink/common/mavlink_msg_scaled_imu2.h \
		mavlink/common/mavlink_msg_log_request_list.h \
		mavlink/common/mavlink_msg_log_entry.h \
		mavlink/common/mavlink_msg_log_request_data.h \
		mavlink/common/mavlink_msg_log_data.h \
		mavlink/common/mavlink_msg_log_erase.h \
		mavlink/common/mavlink_msg_log_request_end.h \
		mavlink/common/mavlink_msg_gps_inject_data.h \
		mavlink/common/mavlink_msg_gps2_raw.h \
		mavlink/common/mavlink_msg_power_status.h \
		mavlink/common/mavlink_msg_serial_control.h \
		mavlink/common/mavlink_msg_gps_rtk.h \
		mavlink/common/mavlink_msg_gps2_rtk.h \
		mavlink/common/mavlink_msg_scaled_imu3.h \
		mavlink/common/mavlink_msg_data_transmission_handshake.h \
		mavlink/common/mavlink_msg_encapsulated_data.h \
		mavlink/common/mavlink_msg_distance_sensor.h \
		mavlink/common/mavlink_msg_terrain_request.h \
		mavlink/common/mavlink_msg_terrain_data.h \
		mavlink/common/mavlink_msg_terrain_check.h \
		mavlink/common/mavlink_msg_terrain_report.h \
		mavlink/common/mavlink_msg_scaled_pressure2.h \
		mavlink/common/mavlink_msg_att_pos_mocap.h \
		mavlink/common/mavlink_msg_set_actuator_control_target.h \
		mavlink/common/mavlink_msg_actuator_control_target.h \
		mavlink/common/mavlink_msg_altitude.h \
		mavlink/common/mavlink_msg_resource_request.h \
		mavlink/common/mavlink_msg_scaled_pressure3.h \
		mavlink/common/mavlink_msg_follow_target.h \
		mavlink/common/mavlink_msg_control_system_state.h \
		mavlink/common/mavlink_msg_battery_status.h \
		mavlink/common/mavlink_msg_autopilot_version.h \
		mavlink/common/mavlink_msg_landing_target.h \
		mavlink/common/mavlink_msg_estimator_status.h \
		mavlink/common/mavlink_msg_wind_cov.h \
		mavlink/common/mavlink_msg_vibration.h \
		mavlink/common/mavlink_msg_home_position.h \
		mavlink/common/mavlink_msg_set_home_position.h \
		mavlink/common/mavlink_msg_message_interval.h \
		mavlink/common/mavlink_msg_extended_sys_state.h \
		mavlink/common/mavlink_msg_adsb_vehicle.h \
		mavlink/common/mavlink_msg_v2_extension.h \
		mavlink/common/mavlink_msg_memory_vect.h \
		mavlink/common/mavlink_msg_debug_vect.h \
		mavlink/common/mavlink_msg_named_value_float.h \
		mavlink/common/mavlink_msg_named_value_int.h \
		mavlink/common/mavlink_msg_statustext.h \
		mavlink/common/mavlink_msg_debug.h \
		mavlink/common_extra_msg/mavlink_msg_cmd_velocity.h \
		mavlink/common_extra_msg/mavlink_msg_cmd_fan_motor_speed.h \
		mavlink/common_extra_msg/mavlink_msg_cmd_worm_motor_speed.h \
		mavlink/common_extra_msg/mavlink_msg_cmd_system.h \
		mavlink/common_extra_msg/mavlink_msg_version.h \
		mavlink/common_extra_msg/mavlink_msg_heart_beat.h \
		mavlink/common_extra_msg/mavlink_msg_imu_data.h \
		mavlink/common_extra_msg/mavlink_msg_odometry_2d.h \
		mavlink/common_extra_msg/mavlink_msg_distance_sensor_data.h \
		mavlink/common_extra_msg/mavlink_msg_mag_sensor.h \
		mavlink/common_extra_msg/mavlink_msg_key.h \
		mavlink/common_extra_msg/mavlink_msg_battery.h \
		mavlink/common_extra_msg/mavlink_msg_time.h \
		mavlink/common_extra_msg/mavlink_msg_sensors_state.h \
		mavlink/common_extra_msg/mavlink_msg_bug_motor_state.h \
		mavlink/common_extra_msg/mavlink_msg_motor_fg.h \
		mavlink/common_extra_msg/mavlink_msg_bug_adc_infra.h \
		mavlink/common_extra_msg/mavlink_msg_led_control.h \
		mavlink/common_extra_msg/mavlink_msg_hardware_error.h \
		mavlink/common_extra_msg/mavlink_msg_cmd_imu.h \
		mavlink/common_extra_msg/mavlink_msg_r16checklist.h \
		mavlink/common_extra_msg/mavlink_msg_startr16test.h \
		mavlink/common_extra_msg/mavlink_msg_vl6180calibration.h \
		mavlink/common_extra_msg/mavlink_msg_pcbachecklist.h \
		mavlink/common_extra_msg/mavlink_msg_test_item_setting.h \
		mavlink/common_extra_msg/mavlink_msg_test_running.h \
		mavlink/common_extra_msg/mavlink_msg_test_reporting.h \
		mavlink/common_extra_msg/mavlink_msg_test_going_on.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o mav_udp.o mav_udp.cpp

uart_robot.o: uart_robot.cpp uart_robot.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o uart_robot.o uart_robot.cpp

uart_rf433.o: uart_rf433.cpp uart_rf433.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o uart_rf433.o uart_rf433.cpp

xml.o: xml.cpp xml.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o xml.o xml.cpp

TestResult.o: TestResult.cpp TestResult.h \
		ui_dialog_test_result.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o TestResult.o TestResult.cpp

qrc_image.o: qrc_image.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o qrc_image.o qrc_image.cpp

moc_mainwindow.o: moc_mainwindow.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_mainwindow.o moc_mainwindow.cpp

moc_led.o: moc_led.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_led.o moc_led.cpp

moc_mav.o: moc_mav.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_mav.o moc_mav.cpp

moc_mav_udp.o: moc_mav_udp.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_mav_udp.o moc_mav_udp.cpp

moc_uart_robot.o: moc_uart_robot.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_uart_robot.o moc_uart_robot.cpp

moc_uart_rf433.o: moc_uart_rf433.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_uart_rf433.o moc_uart_rf433.cpp

moc_xml.o: moc_xml.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_xml.o moc_xml.cpp

moc_TestResult.o: moc_TestResult.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_TestResult.o moc_TestResult.cpp

####### Install

install:  FORCE

uninstall:  FORCE

FORCE:

